config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  get 'tag/index'

  get 'category/:id' => 'blog#by_category', :as => :posts_category
  get 'tag/:id' => 'blog#by_tag', :as => :posts_tag
  get 'date/:year/:month' => 'blog#by_date', :as => :posts_date
  match 'blog/post/:id' => 'blog#show', :as => :post_details, :via => 'get'

  resources :blog do
    resource :comment
  end
  resources :portfolio
  resources :categories

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  has_many :reply, :class_name => 'Comment', :foreign_key => 'reply_to_id'
  belongs_to :reply_to, :class_name => 'Comment'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags

  has_many :comments

  belongs_to :category

  belongs_to :user, :foreign_key => :autor_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/team_role.rb
class TeamRole < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :user

  has_many :social_profile

  has_many :posts
  has_many :portfolios
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_post, only: [:show, :edit]
  before_action :set_categ_tags, only: [:edit, :new]
  before_action :init_widgets, except: [:edit, :new]

  def index
    respond_to do |format|
      format.html
      #format.json { render json: { posts: @posts }, include: [:categories, :user, :tags, :comments] }
      #format.atom
    end
  end

  def show
    @post = @posts.find(params[:id])
    render 'post'
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def by_category
    @category = Category.find(params[:id])
    @description = @category.name
    @posts = @category.posts
    @from = 'category'
    render 'by'
  end

  def by_tag
    @tag = Tag.find(params[:id])
    @description = @tag.name
    @posts = @tag.posts
    @from = 'tag'
    render 'by'
  end

  def by_date
    @posts = Post.where("DATE_PART('month', created_at) = ? and DATE_PART('year',created_at) = ?", params[:month], params[:year])
    @description = params[:month] + '/' + params[:year]
    @from = 'archive'
    render 'by'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def set_categ_tags
      @categories = Category.all.only(:id, :name)
      @tags = Tag.all.only(:id, :name)
    end

    def post_params
      params.require(:post).permit(:title, :content, :visible)
    end

    def init_widgets
      @posts = Post.all.order(created_at: :desc)
      @categories = Category.all.order(name: :desc)
      @tags = Tag.all.order(name: :desc)
      @recents = Post.all.order(created_at: :desc).limit(3)
      @post_months = @posts.group_by { |t| t.created_at.beginning_of_month.to_date  }
    end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/blog/_sidebarPartial.erb
<div id="main-sidebar" class="col-sm-4">

  <!-- ==============================================
  RECENT POST WIDGET
  =============================================== -->
  <div class="widget">

    <h4 class="widget-title">Recent Posts</h4>

    <% unless @recents.blank? %>
        <% @recents.each do |rp| %>
            <div class="media">
              <div class="icon pull-left">
                <%= link_to post_details_path(:id => rp.id), :html => { title: rp.title } do %>
                    <img class="img-responsive" src="http://placehold.it/80x58" alt="" />
                <% end %>
              </div>

              <div class="media-body">
                <p class="small"><%= rp.created_at %></p>
                <p>
                  <%= link_to rp.title, post_details_path(rp) , :html => { title: rp.title } %>
                </p>
              </div>

            </div>
        <% end %>
    <% else %>
        <div class="media">
          <div class="media-body">
            <p>
              No hay post recientemente
            </p>
          </div>
        </div>
    <% end %>
  </div>

  <!-- ==============================================
  SEARCH POST WIDGET
  =============================================== -->
  <div class="widget">

    <!--=== Search Form ===-->

    <form id="search-form" action="#" method="post" novalidate>

      <div class="form-group">
        <div class="controls">
          <input id="search-term" name="searchTerm" placeholder="Search" class="form-control input-lg" type="text">
        </div>
      </div><!-- End name input -->

      <p class="text-center"><button name="submit" type="submit"><i class="fa fa-search"></i></button></p>

    </form><!-- End search-form -->

  </div>

  <!-- ==============================================
  CATEGORIES WIDGET
  =============================================== -->
  <div class="widget">

    <h4 class="widget-title">Categories</h4>

    <ul>
      <% @categories.each do |c| %>
          <li><%= link_to c.name, posts_category_path(:id => c.id) %> </li>
      <% end %>
    </ul>

  </div>

  <!-- ==============================================
  TAGS WIDGET
  =============================================== -->
  <div class="widget">

    <h4 class="widget-title">Tags</h4>

    <div class="tags-container">
      <% unless @tags.blank? %>
          <% @tags.each do |t| %>
              <%= link_to t.name, posts_tag_path(:id => t.id), :class => 'tag' %>
          <% end %>
      <% else %>
          <p>No exiten etiquetas</p>
      <% end %>
    </div>

  </div>

</div>

app/views/blog/by.html.erb
<section class="white-bg padding-top-bottom">
  <div class="container">
    <div class="row">
      <% case @from %>
        <% when 'category' %>
          <h1 class="section-title">By Category</h1>
        <% when 'tag' %>
          <h1 class="section-title">By Tag</h1>
        <% when 'archive' %>
          <h1 class="section-title">By Date</h1>
      <% end %>

      <p class="section-description">
        <%= @description %>
      </p>

      <div class="post-by">

      </div>
    </div>
  </div>
</section>

app/views/blog/index.html.erb
<% content_for :header do %>
  <!-- ==============================================
  HEADER
  =============================================== -->
    <header id="inner-page-header" class="parallax-bg" data-parallax-background="assets/blog/blog-header-3.jpg" data-stellar-background-ratio=".3">

      <div class="header-content">

        <h1 class="bordered-text">We <span class="primary">Love</span> Writing</h1>

      </div>

    </header><!--End header -->
<% end %>

<!-- ==============================================
BLOG LIST
=============================================== -->
<section class="white-bg padding-top-bottom">

  <div class="container">

    <div class="row">

      <div id="blog-list" class="col-sm-8">

        <% @posts.each do |p| %>
            <article class="post-entry">

              <header class="post-header">

                <h2 class="post-title">
                  <%= link_to post_details_path(p), :html => { title: p.title } do %>
                    <%= p.title %>
                  <% end %>
                </h2>

                <ul class="post-meta small">
                  <li><i class="fa fa-calendar"></i><a href="#"><%= p.created_at.to_date.to_formatted_s :long %></a></li>
                  <li><i class="fa fa-comments-o"></i><a href="#"><%= p.comments.count %> Comment(s)</a></li>
                  <li><i class="fa fa-folder-open-o"></i>
                    <%= link_to p.category.name, posts_category_path(:id => p.category.id) %>
                  </li>
                </ul>

                <%= link_to post_details_path(p), :class => 'post-thumb', :html => { title: p.title } do %>
                    <img class="img-responsive" src="http://placehold.it/945x540" alt="" />
                <% end %>
              </header>

              <p>
                <%= p.summary.html_safe %>
              </p>

              <%= link_to 'Continue Reading', post_details_path(p), :class => 'post-link', :html => { title: p.title } %>

            </article>
        <% end %>

        <!-- Pagination -->

        <nav class="text-center">
          <ul class="pagination">
            <li><a href="#"><span aria-hidden="true"><i class="fa fa-caret-left"></i></span><span class="sr-only">Previous</span></a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#"><span aria-hidden="true"><i class="fa fa-caret-right"></i></span><span class="sr-only">Next</span></a></li>
          </ul>
        </nav>

      </div>

      <%= render :partial => 'sidebarPartial' %>

    </div>

  </div>

</section>

app/views/blog/post.html.erb
<!-- ==============================================
SINGLE POST
=============================================== -->
<section class="white-bg padding-top-bottom">

  <div class="container">

    <div class="row">

      <div id="single-post" class="col-sm-8">

        <article class="post-entry">

          <header class="post-header">
            <h2 class="post-title"><%= @post.title %></h2>

            <ul class="post-meta small">
              <li><i class="fa fa-calendar"></i><a href="#"><%= @post.created_at.to_date.to_formatted_s :long %> </a></li>
              <li><i class="fa fa-comments-o"></i><a href="#"><%= @post.comments.count %> Comment(s)</a></li>
              <li><i class="fa fa-folder-open-o"></i>
                <%= link_to @post.category.name, posts_category_path(:id => @post.category.id) %>
              </li>
            </ul>

            <img class="img-responsive" src="http://placehold.it/945x540" alt="" />
          </header>

          <p class="post-summary" style="font-style: italic">
            <%= @post.summary.html_safe %>
          </p>

          <br/>

          <div>
            <%= @post.content.html_safe %>
          </div>

          <% unless @post.tags %>
              <footer class="post-footer">

                <div class="tags-container text-right">

                  <i class="fa fa-tags"></i>

                  <% @post.tags.each do |t| %>
                      <%= link_to t.name, posts_tag_path(:id => t.id), :class => 'tag' %>
                  <% end %>
                </div>

              </footer>
          <% end %>

        </article>

        <div class="post-comments">

          <h2>3 Comments</h2>

          <ul class="media-list">

            <li class="media">

              <a class="media-left" href="#">
                <img class="img-circle" src="http://placehold.it/80x80" alt="...">
              </a>

              <div class="media-body">
                <div class="media-heading">

                  <h5>John</h5>
                  <small class="comment-date">12 November 2014</small>

                </div>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vestibulum sodales dapibus. Proin pellentesque semper odio quis molestie. </p>

                <a class="reply-link" href="#reply">Reply</a>

                <div class="replies"><span>1 Reply</span></div>

                <div class="media">

                  <a class="media-left" href="#">
                    <img class="img-circle" src="http://placehold.it/80x80" alt="...">
                  </a>

                  <div class="media-body">

                    <div class="media-heading">

                      <h5>Jane</h5>
                      <small class="comment-date">12 November 2014</small>

                    </div>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vestibulum sodales dapibus. Proin pellentesque semper odio quis . </p>

                    <a class="reply-link" href="#reply">Reply</a>
                  </div>

                </div>

              </div>

            </li>

            <li class="media">

              <a class="media-left" href="#">
                <img class="img-circle" src="http://placehold.it/80x80" alt="...">
              </a>

              <div class="media-body">

                <div class="media-heading">

                  <h5>Peter</h5>
                  <small class="comment-date">12 November 2014</small>

                </div>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vestibulum sodales dapibus. Proin pellentesque semper odio quis . </p>

                <a class="reply-link" href="#reply">Reply</a>

              </div>

            </li>

          </ul>

          <!--=== Comment Form ===-->

          <form id="comment-form" action="#" method="post" novalidate>

            <div class="form-header">
              <h3>Leave a Comment</h3>
            </div>

            <div class="row">

              <div class="col-sm-6">

                <div class="form-group">
                  <label class="control-label" for="comment-name">Name</label>
                  <div class="controls">
                    <input id="comment-name" name="commentName" placeholder="Name *" class="form-control" type="text">
                  </div>
                </div>

              </div>

              <div class="col-sm-6">

                <div class="form-group">
                  <label class="control-label" for="comment-mail">Email</label>
                  <div class=" controls">
                    <input id="comment-mail" name="commentEmail" placeholder="Email *" class="form-control" type="email">
                  </div>
                </div>

              </div>

            </div>

            <div class="form-group">
              <label class="control-label" for="comment-website">Website</label>
              <div class=" controls">
                <input id="comment-website" name="commentWebsite" placeholder="Website (Optional)" class="form-control" type="text">
              </div>
            </div>

            <div class="form-group">
              <label class="control-label" for="comment">Message</label>
              <div class="controls">
                <textarea id="comment" name="comment"  placeholder="Comment *" class="form-control" rows="8"></textarea>
              </div>
            </div>

            <p><button name="submit" type="submit" class="btn btn-quattro"><i class="fa fa-comment"></i>Submit comment</button></p>

          </form><!-- End comment-form -->

        </div>

      </div>

      <%= render :partial => 'sidebarPartial' %>

    </div>

  </div>

</section>