config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  get 'tag/index'

  get 'category/:id' => 'blog#by_category', :as => :posts_category
  get 'tag/:id' => 'blog#by_tag', :as => :posts_tag
  get 'date/:year/:month' => 'blog#by_date', :as => :posts_date
  match 'blog/post/:id' => 'blog#show', :as => :post_details, :via => 'get'

  resources :blog do
    resource :comment
  end
  resources :portfolio
  resources :categories

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  has_many :reply, :class_name => 'Comment', :foreign_key => 'reply_to_id'
  belongs_to :reply_to, :class_name => 'Comment'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags

  has_many :comments

  belongs_to :category

  belongs_to :user, :foreign_key => :autor_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/team_role.rb
class TeamRole < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :user

  has_many :social_profile

  has_many :posts
  has_many :portfolios
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_post, only: [:show, :edit]
  before_action :set_categ_tags, only: [:edit, :new]
  before_action :init_widgets, except: [:edit, :new]

  def index
    respond_to do |format|
      format.html
      #format.json { render json: { posts: @posts }, include: [:categories, :user, :tags, :comments] }
      #format.atom
    end
  end

  def show
    @post = @posts.find(params[:id])
    render 'post'
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def by_category
    @category = Category.find(params[:id])
    @description = @category.name
    @posts = @category.posts
    @from = 'category'
    render 'by'
  end

  def by_tag
    @tag = Tag.find(params[:id])
    @description = @tag.name
    @posts = @tag.posts
    @from = 'tag'
    render 'by'
  end

  def by_date
    @posts = Post.where("DATE_PART('month', created_at) = ? and DATE_PART('year',created_at) = ?", params[:month], params[:year])
    @description = params[:month] + '/' + params[:year]
    @from = 'archive'
    render 'by'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def set_categ_tags
      @categories = Category.all.only(:id, :name)
      @tags = Tag.all.only(:id, :name)
    end

    def post_params
      params.require(:post).permit(:title, :content, :visible)
    end

    def init_widgets
      @posts = Post.all.order(created_at: :desc)
      @categories = Category.all.order(name: :desc)
      @tags = Tag.all.order(name: :desc)
      @recents = Post.all.order(created_at: :desc).limit(3)
      @post_months = @posts.group_by { |t| t.created_at.beginning_of_month.to_date  }
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <title>FSDTeam</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- ==============================================
  Favicons
  =============================================== -->
  <!--<link rel="shortcut icon" href="assets/favicon.ico">-->
  <!--<link rel="apple-touch-icon" href="assets/apple-touch-icon.png">-->
  <!--<link rel="apple-touch-icon" sizes="72x72" href="assets/apple-touch-icon-72x72.png">-->
  <!--<link rel="apple-touch-icon" sizes="114x114" href="assets/apple-touch-icon-114x114.png">-->

  <!-- ==============================================
  CSS
  =============================================== -->
  <%= stylesheet_link_tag 'application' %>

  <!-- ==============================================
  JavaScripts
  =============================================== -->
  <%= javascript_include_tag 'modernizr.min' %>

  <%= csrf_meta_tags %>

</head>
<body data-spy="scroll" data-target="#main-nav" data-offset="400">

  <!--=== PAGE PRELOADER ===-->
  <div id="page-loader"><span class="page-loader-gif">Loading...</span></div>

  <% if content_for?(:header) %>
    <%= yield :header %>
  <% end %>

  <!-- ==============================================
  MAIN NAV
  =============================================== -->

  <div id="main-nav" class="navbar">
    <div class="container">

      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
          <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button>

        <!-- ======= LOGO ========-->
        <%= link_to root_path+'#home', :class => 'navbar-brand scrollto' do %>
            <img class="site-logo" src="http://placehold.it/90x40?text=LOGO+90x40" alt="LOGO 90x40" />
        <% end %>
      </div>

      <div id="site-nav" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="sr-only">
            <%= link_to 'Home', root_path, { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'About', root_path+'#about', { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'Services', root_path+'#services', { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'Portfolio', root_path+'#portfolio', { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'Team', root_path+'#team', { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'Blog', root_path+'#news', { class: 'scrollto'} %>
          </li>
          <li>
            <%= link_to 'Contact', root_path+'#contact', { class: 'scrollto'} %>
          </li>
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Wellcome <%= current_user.name %>!!! <i class="fa fa-user"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
                  <li><%= link_to root_path do %><i class="fa fa-cog"></i> Administrar<% end %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to sign_in_url do %><i class="fa fa-user"></i><% end %></li>
          <% end %>
        </ul>
      </div><!--End navbar-collapse -->

    </div><!--End container -->

  </div><!--End main-nav -->

  <%= yield %>

  <!-- ==============================================
  FOOTER
  =============================================== -->
  <footer id="main-footer">

    <div class="container text-center">

      <img class="img-responsive img-center footer-logo" src="http://placehold.it/140x70?text=LOGO+140x70" alt="LOGO 140x70" />

      <ul class="social-links">
        <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-google-plus fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-dribbble fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
      </ul>
      <p>&copy;2016 FSD Theme by <a href="#" target="_blank">FSD Team</a></p>

    </div>

  </footer>

  <!-- ==============================================
  SCRIPTS
  =============================================== -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <script>

    var mapPoint = {
      'lat': 40.720099,
      'lng': -74.005764,
      'zoom' : 15,
      'infoText':'<p>250 W Broadway\
                  <br/>New York\
                  <br/>NY 10013</p>',
      'linkText':'View on Google Maps',
      'mapAddress':'250 W Broadway, New York, NY 10013',
      'icon': 'assets/marker.png'
    };

  </script>

  <% if content_for?(:scripts) %>
    <%= yield :scripts %>
  <% end %>
</body>
</html>